# Wrangler configuration for Guess the Masterpiece Quiz App  
name = "masterpiece-quiz-pages"
compatibility_date = "2024-09-25" 
pages_build_output_dir = ".svelte-kit/output/static"

# Environment variables are managed via Cloudflare Pages dashboard