# Wrangler configuration for Guess the Masterpiece Quiz App  
name = "masterpiece-quiz-prod"
compatibility_date = "2024-09-25" 
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/output/client/_worker.js"
account_id = "25a2df56c26faf86bc9de7a9f31fbc9a"

# Environment variables are managed via Cloudflare Pages dashboard